### ISSUE TITLE
#1 Game still in progress help wanted 

### ISSUE THREAD

**Issue by ClownApril** [peleon02/PUBG-Battlepoint-FarmBot#1]
After the new update game loads up but can't interact with pubg any fix soon?

**Comment by ClownApril** [comment]
Cant interact with game, control denied

**Comment by ClownApril** [comment]
Powershell:
 File "C:\Users\Kiki\Desktop\PUBG-Battlepoint-FarmBot-afkbot2.4\botgui.py", line 77, in <lambda>
    self.teneighty.clicked.connect(lambda: self.set_res('1080'))
  File "C:\Users\Kiki\Desktop\PUBG-Battlepoint-FarmBot-afkbot2.4\botgui.py", line 159, in set_res
    bot.setConfig(res.strip())
  File "C:\Users\Kiki\Desktop\PUBG-Battlepoint-FarmBot-afkbot2.4\FarmBot.py", line 40, in setConfig
    with open('configRes.json', encoding='UTF-8') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'configRes.json'

**Comment by ehwjwisid** [comment]
Still tryied everything it stays on the main menu on pubg without doing anything

**Comment by peleon02** [comment]
Do you have this file? configRes.json
Here says no FileNotFoundError: [Errno 2] No such file or directory: 'configRes.json'

**Comment by ClownApril** [comment]
yes i have it in the same folder bro
redownloaded it twice idk why :p 
still nothing is it working for you?

**Comment by peleon02** [comment]
yep

**Comment by ClownApril** [comment]
why isn't it reading configRes.json?

**Comment by ClownApril** [comment]
if anyone can help me please? I would open teamviewer with or anything to fix my bot?

**Comment by peleon02** [comment]
Will add you in disc in one hour

**Comment by ClownApril** [comment]
It's working <3 Thanks for everything man
