### ISSUE TITLE
Don't earning BP's

### ISSUE THREAD

**Issue by SerjRamone** [peleon02/PUBG-Battlepoint-FarmBot#15]
The bot works but I don't earn BP's
How to fix it?

**Comment by D3Qz** [comment]
They have fixed it 
Now bot need to take any weapon to ger BP

**Comment by peleon02** [comment]
That could be so hard and bannable, because it needs an ESP

**Comment by D3Qz** [comment]
Yeah so the era of bots has finished

**Comment by D3Qz** [comment]
I think it's a ESP function so u can be banned
