### ISSUE TITLE
Works sometimes, sometimes not.

### ISSUE THREAD

**Issue by Crusage** [peleon02/PUBG-Battlepoint-FarmBot#2]
It's kinda weird, i once tested it just to see if it worked and it worked prefectly. And then i stopped it, and later i started it again, and it opened pubg like it was supposed to. But nothing else happened. I dont know why this happens. Its like after i click stop i cant start it again, except if i wait half an hour or something, its really confusing.

Edit: Also, i just realized it stops after one time. It doesnt find new match and repeats
Edit2: I think i saw the fix on your mpgh post, but i can't change the cmd directory since the file is in D: and not C:

**Comment by ehwjwisid** [comment]
I am on C: it doesn't work for me anyway its the file not from your pc or something

**Comment by peleon02** [comment]
I dont know what´s happening this days, I have to try it, because it could be a PUBG patch or something idk (I dont think so) Just copy to C:\ and try it

**Comment by Crusage** [comment]
Now it works all the time, probably just a glitch the first few times, where it wouldnt work if i didnt wait half an hour... And i figured how to change directory to another drive in cmd. My file is in the D drive, so i had to type D: in cmd, and it just changed drive, and then i could type: "cd *folder location*" And it worked perfectly. But it still doesnt want to repeat, it does it one time, and i get my 60bps, it leaves the match, but it doesnt search for new one.

**Comment by peleon02** [comment]
I will be doing TeamViewer or discord in one hour PantsAreMao #9776

**Comment by peleon02** [comment]
No more activity, Closed
