### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ovladuk** [peleon02/PUBG-Battlepoint-FarmBot#3]
was working for me before pubg updated. it loads up pubg but then just stays on "loading pubg".

**Comment by ClownApril** [comment]
same here man.. so it's not only me and I was freaking out for 2 days in a row

**Comment by peleon02** [comment]
I will be doing TeamViewer in 1 h if you want add me on discord PantsAreMao#9776

**Comment by ClownApril** [comment]
added

**Comment by peleon02** [comment]
Call me

**Comment by ovladuk** [comment]
not on discord. did you find out why it isn't working?

**Comment by ClownApril** [comment]
go update now it works after the new pubg fixes now <3

**Comment by ClownApril** [comment]
can you please fix servers are busy and want to reconnect to your previous match ( button click to work )

**Comment by peleon02** [comment]
I cant, fix the dead, you have tyo wait, and the other buttons work

**Comment by ehwjwisid** [comment]
Not all of the buttons do.. reconnect to previous match and servers are busy don't work.. all the other things work

**Comment by peleon02** [comment]
resolution?

**Comment by ehwjwisid** [comment]
1080
Anyway why does the bot stops 
I try like 10 times until 1runs correctly and leaves the bot all day running

**Comment by ClownApril** [comment]
You have earned 240BPs
Click on cancel just i case that the reconnect button is there
Click the reconnect msg in case servers are busy
Cant interact with game, control denied
Cant interact with game, control denied

**Comment by ehwjwisid** [comment]
I changed the timeout its working

**Comment by peleon02** [comment]
<3
