### ISSUE TITLE
Beta stays in the game longer

### ISSUE THREAD

**Issue by Meliodastablet** [peleon02/PUBG-Battlepoint-FarmBot#4]
Hey man, I realized that [beta] bot stays in the game approximately 1 minutes longer but because we are getting the same amount of bp, its a waste of time. It also waits longer in menu etc. If you can somehow optimize that waiting time that would be great. I was thinking, 20 seconds after clicking to the exit to menu button, if bot clicks to the place where reconnect button should be(even if there is no issue) things can go faster. If there is no reconnect issue, fine, clicking on empty space won't harm anyone. If there is a reconnect button therr, this should save time. Thanks for your efforts, I really appreciate it.

**Comment by peleon02** [comment]
<3
