### ISSUE TITLE
Can you make the bot exit on itself when my character dies?

### ISSUE THREAD

**Issue by COMMANDERWONG** [peleon02/PUBG-Battlepoint-FarmBot#5]

**Comment by peleon02** [comment]
It has to wait until it will exit in the normal way I can't do other thing

**Comment by COMMANDERWONG** [comment]
ok...But can I make the time shorter by changing the script???

**Comment by peleon02** [comment]
ofc, go to this line 	timeout = time() + 315 - wait_for_plane and change the 315 but it could give you 0 bps

**Comment by COMMANDERWONG** [comment]
I would like to ask,does the "315" stand for seconds???
