### ISSUE TITLE
Running on dedicated server

### ISSUE THREAD

**Issue by pubgrad** [peleon02/PUBG-Battlepoint-FarmBot#6]
Can I run this dedicated server in the cloud? It has 4 core cpu and gt710. I know that specs can run pubg on very low settings but will your farmbot work if I close rdp client with which I am connected to that server but game will be running in the background?

Btw is this full automatic or I have to site click to exit lobby and start another game or I just run it and leave it will give me 6k bp in 8 hours?

**Comment by peleon02** [comment]
You have to know the resolution, so it needs a monitor and you will be getting 5k 8 hours

**Comment by pubgrad** [comment]
But I will be connected to it from my pc via rdp client and I will choose my monitor resolution but after doing that I will close rdp, will it still work?
